function getData() {
  return [
    {
      id: 3245,
      name: "David Bord",
      title: "Flying Wings",
      ranking: 2,
      image: "",
      like: 4759,
      forward: 134,
      popularity: 2342,
    },
    {
      id: 1534,
      name: "Lucy",
      title: "Growing up trouble",
      ranking: 1,
      image: "",
      like: 4759,
      forward: 134,
      popularity: 2342,
    },
    {
      id: 123,
      name: "Jerry Cool West",
      title: "Sculptor's diary",
      ranking: 4,
      image: "",
      like: 4759,
      forward: 134,
      popularity: 2342,
    },
    {
      id: 3324,
      name: "Bold",
      title: "illustration of little girl",
      ranking: 3,
      image: "",
      like: 4759,
      forward: 134,
      popularity: 2342,
    },
    {
      id: 3242,
      name: "David Bord",
      title: "Flying Wings",
      ranking: 5,
      image: "",
      like: 4759,
      forward: 134,
      popularity: 2342,
    },
    {
      id: 1533,
      name: "Lucy",
      title: "Growing up trouble",
      ranking: 6,
      image: "",
      like: 4759,
      forward: 134,
      popularity: 2342,
    },
    {
      id: 1234,
      name: "Jerry Cool West",
      title: "Sculptor's diary",
      ranking: 7,
      image: "",
      like: 4759,
      forward: 134,
      popularity: 2342,
    },
    {
      id: 3224,
      name: "Bold",
      title: "illustration of little girl",
      ranking: 8,
      image: "",
      like: 4759,
      forward: 134,
      popularity: 2342,
    },
  ];
}
